CREATE TABLE `users_stripe_card` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `address_city` varchar(255) DEFAULT NULL,
  `address_country` varchar(255) DEFAULT NULL,
  `address_line1` varchar(255) DEFAULT NULL,
  `address_line1_check` varchar(255) DEFAULT NULL,
  `address_line2` varchar(255) DEFAULT NULL,
  `address_state` varchar(255) DEFAULT NULL,
  `address_zip` varchar(255) DEFAULT NULL,
  `address_zip_check` varchar(255) DEFAULT NULL,
  `brand` varchar(255) NOT NULL,
  `country` varchar(255) NOT NULL,
  `cvc_check` varchar(255) DEFAULT NULL,
  `dynamic_last4` varchar(255) DEFAULT NULL,
  `exp_month` int(11) NOT NULL,
  `exp_year` int(11) NOT NULL,
  `funding` varchar(255) DEFAULT NULL,
  `card_id` varchar(255) DEFAULT NULL,
  `last4` varchar(255) NOT NULL,
  `metadata` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `object` varchar(255) DEFAULT NULL,
  `tokenization_method` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;